### ISSUE TITLE
Add web analytics

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref.github.io#12]
It should be pretty easy to add any necessary headers to `_layouts/base.html`.

**Comment by hlapp** [comment]
Yes in principle. Though web analytics scripts are normally put near the bottom of the page (so that difficulties with executing the code block don't delay loading the page) 😄

**Comment by hlapp** [comment]
Implemented through d38597f69bc7bddeec0408c593113c7a3dec3325 and e9c347b0e8e2f7179f8e2177800fe2462b7b0b07.
